### ISSUE TITLE
Detected I/O inside the event loop

### ISSUE THREAD

**Issue by KameDomotics** [atxbyea/samsungrac#1]
Hi, I had installed Climate_Ip from your forked repo, but I have the same issue: when I give a command, this error appears in the log "Detected I/O inside the event loop"

**Comment by atxbyea** [comment]
I'll have a look at it when I have time, no issues for me here atleast, works fine, but I know this is a known issue with a lot of custom components @KameDomotics

**Comment by elfhack** [comment]
I actually have a patch for this, I'll do a PR soonish

**Comment by KameDomotics** [comment]
> I actually have a patch for this, I'll do a PR soonish

It’s fantastic! Thanks

**Comment by wifi75** [comment]
@atxbyea hello, from Ha it is possible update ? Or I must update from custom folder ?

**Comment by atxbyea** [comment]
@elfhack wonderful, please submit and I'll take a look

**Comment by atxbyea** [comment]
@wifi75 I merged with HACS today, so it should be avaliable sometime soon I guess.

**Comment by wifi75** [comment]
which component name?

**Comment by wifi75** [comment]
@atxbyea  it is ok already found on Home assistant !

very good

**Comment by KameDomotics** [comment]
I have installed 3.1 version, but same problem persist.

I also tried to uninstall and reinstall from scratch, but the error persists


`Logger: homeassistant.util.async_
Source: util/async_.py:105 
First occurred: 19:38:39 (6 occurrences) 
Last logged: 19:39:48

Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for climate_ip doing I/O at custom_components/climate_ip/connection_request.py, line 105: resp = session.request(**self._params) `

I have this problem after HomeAssistant 0.110 update, before was no problems...

**Comment by KameDomotics** [comment]
At line 105 of connection_request.py i have this:

:
                    resp = session.request(**self._params)
                    self.logger.info(
                        "Command executed with code: {}, text: {}".format(
                            resp.status_code, resp.text
                        )
                    )

**Comment by KameDomotics** [comment]
please @atxbyea @ishioni  i am getting too many indications and changes to make, i don't understand anything anymore and i can't solve the problem. ☹️

Now, I have already installed (new installation from zero) climate_ip 3.1 from HACS... now what should i do?

**Comment by atxbyea** [comment]
@elfhack @KameDomotics @wifi75 I have now merged the PRs from @ishioni thanks again 👍

**Comment by ishioni** [comment]
@atxbyea I made a typo in my last PR, please pull #8

**Comment by atxbyea** [comment]
Release 3.2 should be out now with @ishioni fixes @KameDomotics

**Comment by KameDomotics** [comment]
unfortunately I always have the same problem even with v3.2 ☹️

`Logger: homeassistant.util.async_
Source: util/async_.py:105 
First occurred: 13:10:37 (1 occurrences) 
Last logged: 13:10:37

Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for climate_ip doing I/O at custom_components/climate_ip/connection_request.py, line 105: resp = session.request(**self._params) `

I have a Samsung AR7000
This is my configuration:

climate:
  - platform: climate_ip
    name: Samsung AC   
    config_file: 'samsungrac.yaml'
    ip_address: '192.168.1.15'
    token: 'my token'
    cert: 'ac14k_m.pem'
    poll: true

**Comment by KameDomotics** [comment]
FANTASTIC! now finally it works well, and the Warning “Detected I/O event inside the loop” appear only one time after HA reboot (before it always appeared at every operation).

Only one question:
now "none" appears as in the image.  how can i delete it?  (before it was not there)
![BD964CE3-37C6-450B-96C5-D72D02D46DA4](https://user-images.githubusercontent.com/47695661/95324828-9b67e900-08a0-11eb-985c-007252a1c2a5.jpeg)



thank you for your excellent work!

**Comment by Poncharello** [comment]
Hi @atxbyea,
hi @ishioni 
From the latest 2021.4 HA changelog:

Core / Custom integrations

Block detectable I/O in the event loop

We added a warning when this happens last April and gave developers a year to fix the instability. We now prevent the instability by raising RuntimeError when code attempts to do known I/O in the event loop instead of the executor.

We now provide a suggestion on how to fix the code that is causing the issue.

(@bdraco - #48387)


I think this is going to be a very big problem, 'cause from this HA version the "I/O event inside the loop" Warning will become blocking.
